services:
  chatsimplesdb:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=chatsimplesdb'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'